### ISSUE TITLE
possible grammatical error in i3 config?

### ISSUE THREAD

**Issue by 3y3p4tch** [safinsingh/dots#1]
Hi, thanks for the dotfiles, they are quite helpful. I was reading the config to make certain modifications of my own, and I noticed that on [line 20 of i3 config](https://github.com/safinsingh/dots/blob/master/.config/i3/config#L20), it's probably misspelled? (*picom* instead of _phicom_?)

Anyway, thanks for the nice config, I really appreciate it

**Comment by safinsingh** [comment]
Nope, it's not a typo! I'm not using picom -- phicom is a fork of picom that isn't available on the AUR or through my dots.
